theme: jekyll-theme-slate
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - README.md
  - bt_bst.md
  - collection.md
  - array.md
  - string.md
  - dfs_backtracking.md
  - graph.md
  - bfs.md


